### ISSUE TITLE
Nuxt Module best practices

### ISSUE THREAD

**Issue by atinux** [ihavecoke/nuxt-seo-meta#1]
Hi @ihavecoke 

To respect Nuxt standard, I suggest:
- Using `inject` in your plugin and recommend to use `$seoMeta`, see https://nuxtjs.org/docs/2.x/directory-structure/plugins#inject-in-root--context
- Rename the repo and module to `nuxt-seo-meta`
- Document the options only with `seoMeta` property in `nuxt.config.js` for simplicity
- Use defu for defaults options: https://github.com/nuxt-community/color-mode-module/blob/master/lib/module.js#L19-L22

We are working on creating the best practices for Nuxt modules so it would be easier in the future :)
In the meantime, I recommend to checkout https://github.com/nuxt-community/module-template/tree/template to learn a bit more :)

**Comment by ihavecoke** [comment]
@Atinux thanks for you review. let me do you suggest one by one :)

**Comment by ihavecoke** [comment]
hi @Atinux i just follow you suggest to change the module name or other options, can you review this repo again? thks :)

**Comment by atinux** [comment]
Hi @ihavecoke 

I tried to checkout the demo directory but I got an error: https://codesandbox.io/s/github/ihavecoke/nuxt-seo-meta/tree/main/demo?file=/pages/index.vue

![Screenshot 2021-01-11 at 13 18 03](https://user-images.githubusercontent.com/904724/104181640-7212a800-540f-11eb-9afd-b8a6140bcba4.png)

**Comment by ihavecoke** [comment]
@Atinux i have just fixed the issue with these changes https://github.com/ihavecoke/nuxt-seo-meta/commit/72b4b3e15554a41581f6f03d1fb76a100b7172ea. :). by the way the demo page are poor now, but i have plan to add more content to explain how the npm works. so the `nuxt-seo-meta` repo also under development. some doc or api not perfect

**Comment by pi0** [comment]
Hi @ihavecoke . Checking the latest code seems everything is cool for Nuxt2. It would be nice as next step, trying to check and ensure module is compatible with Nuxt bridge (more info: https://v3.nuxtjs.org/getting-started/migration#module-migration).

**Comment by ihavecoke** [comment]
> Hi @ihavecoke . Checking the latest code seems everything is cool for Nuxt2. It would be nice as next step, trying to check and ensure module is compatible with Nuxt bridge (more info: https://v3.nuxtjs.org/getting-started/migration#module-migration).

Good idea
